name: aeros_design_system_example
description: Example showcasing every Aeros Design System widget.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  aeros_design_system:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
